server.port=8081
spring.application.name=post-service

# Database
spring.datasource.url=jdbc:postgresql://postgres:5432/newhan_posts
spring.datasource.username=admin
spring.datasource.password=admin123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Kafka
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:29092}
spring.kafka.consumer.group-id=post-service-group

# --- NEW: KAFKA DESERIALIZATION & MAPPING ---
# 1. Key Deserializer
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# 2. Value Deserializer (Using ErrorHandling so bad messages don't crash the app)
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer

# 3. Map the User Service DTO to the Post Service DTO
spring.kafka.consumer.properties.spring.json.type.mapping=com.newhan.userservice.dto.UserUpdateEvent:com.newhan.postservice.dto.UserUpdateEvent
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

jwt.secret=your-super-secret-and-long-key-that-is-not-nyakyv-taen-klyuch

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
FILE_UPLOAD_DIR=./uploads