server.port=8081
spring.application.name=post-service

# Database
spring.datasource.url=jdbc:postgresql://postgres:5432/newhan_posts
spring.datasource.username=admin
spring.datasource.password=admin123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Kafka
spring.kafka.bootstrap-servers=kafka:29092
spring.kafka.consumer.group-id=post-service-group

jwt.secret=your-super-secret-and-long-key-that-is-not-nyakyv-taen-klyuch

# --- FIX 1: INCREASE FILE SIZE LIMITS ---
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# --- FIX 2: CHANGE UPLOAD DIR FOR LOCAL TESTING ---
# If running on Windows, use a relative path like "./uploads"
FILE_UPLOAD_DIR=./uploads