package com.newhan.chatservice.service;

import com.newhan.chatservice.dto.messagedtos.ChatMessageDTO;
import com.newhan.chatservice.dto.messagedtos.SendMessageDTO;
import com.newhan.chatservice.model.chatmessage.ChatMessage;
import com.newhan.chatservice.model.chatmessage.MessageSatus;
import com.newhan.chatservice.repository.ChatMessageRepository;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.util.Date;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

@ExtendWith(MockitoExtension.class)
class ChatMessageServiceTest {

    @Mock
    private ChatMessageRepository chatMessageRepository;

    // Note: UserRepository is no longer needed here because 
    // validation happens at the Controller/Security level, not inside saveMessage logic.

    @InjectMocks
    private ChatMessageService chatMessageService;

    @Test
    void saveMessage_Success() {
        // Arrange
        String senderId = "user-uuid-1";
        String recipientId = "user-uuid-2";
        
        // Input DTO
        SendMessageDTO dto = new SendMessageDTO("Hello World", recipientId);

        // Mocked Saved Entity (Returned by Repository)
        ChatMessage savedMessage = new ChatMessage();
        savedMessage.setId("mongo-object-id-123"); // ID generated by Mongo
        savedMessage.setSenderId(senderId);
        savedMessage.setRecipientId(recipientId);
        savedMessage.setContent("Hello World");
        savedMessage.setTimestamp(new Date()); // Mongo uses Date
        savedMessage.setStatus(MessageSatus.DELIVERED);
        // Note: The service generates the chatId "user-uuid-1_user-uuid-2" internally before saving
        
        when(chatMessageRepository.save(any(ChatMessage.class))).thenReturn(savedMessage);

        // Act
        ChatMessageDTO result = chatMessageService.saveMessage(dto, senderId);

        // Assert
        assertNotNull(result);
        assertEquals("Hello World", result.content());
        assertEquals(senderId, result.senderId());
        assertEquals(recipientId, result.recipientId());
        assertNotNull(result.timestamp()); // Check that Date was converted to LocalDateTime
        
        verify(chatMessageRepository).save(any(ChatMessage.class));
    }

    @Test
    void findChatMessages_Success() {
        // Arrange
        String userA = "alice";
        String userB = "bob";
        
        // The service logic sorts IDs alphabetically: "alice_bob"
        String expectedChatId = "alice_bob";
        
        ChatMessage msg1 = ChatMessage.builder()
                .chatId(expectedChatId)
                .senderId(userA)
                .recipientId(userB)
                .content("Hi")
                .timestamp(new Date(System.currentTimeMillis() - 10000))
                .build();
        
        ChatMessage msg2 = ChatMessage.builder()
                .chatId(expectedChatId)
                .senderId(userB)
                .recipientId(userA)
                .content("Hello")
                .timestamp(new Date())
                .build();

        // Mock the Repository findByChatId
        when(chatMessageRepository.findByChatId(expectedChatId))
                .thenReturn(List.of(msg1, msg2));

        // Act
        List<ChatMessageDTO> history = chatMessageService.findChatMessages(userA, userB);

        // Assert
        assertEquals(2, history.size());
        assertEquals("Hi", history.get(0).content());
        assertEquals("Hello", history.get(1).content());
        
        // Also verify it works if we swap parameters (Bob checks history with Alice)
        List<ChatMessageDTO> historyReverse = chatMessageService.findChatMessages(userB, userA);
        assertEquals(2, historyReverse.size());
    }
}