server.port=8082
spring.application.name=api-gateway

# --- CORS Configuration (Allow everything for mobile app) ---
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,DELETE,PATCH
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*

# --- Routes Configuration ---

# Route 1: Chat Service (Users & Auth)
spring.cloud.gateway.routes[0].id=chat-service
spring.cloud.gateway.routes[0].uri=http://chat-service:8080
# Note: Comma separated paths work for the Path predicate
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/users/**, /api/messagages/**

# Route 2: Chat Service (WebSockets)
# Use 'ws://' schema so the gateway keeps the connection alive
spring.cloud.gateway.routes[1].id=chat-websocket
spring.cloud.gateway.routes[1].uri=ws://chat-service:8080
spring.cloud.gateway.routes[1].predicates[0]=Path=/ws-chat/**

# Route 3: Post Service (New!)
spring.cloud.gateway.routes[2].id=post-service
spring.cloud.gateway.routes[2].uri=http://post-service:8081
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/posts/**