# --- APP & DATABASE ---
spring.application.name=newhanchat
spring.data.mongodb.uri=mongodb://localhost:27017/chatdb

# --- SECURITY ---
jwt.secret=your-super-secret-and-long-key-that-is-not-nyakyv-taen-klyuch

# --- KAFKA CONFIGURATION ---
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:29092}

# Consumer Config (To listen for updates)
spring.kafka.consumer.group-id=newhanchat-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer

# Event Mapping
spring.kafka.consumer.properties.spring.json.type.mapping=com.newhan.userservice.dto.UserUpdateEvent:com.newhan.chatservice.dto.userdtos.UserUpdateEvent,com.newhan.userservice.dto.UserStatusUpdateEvent:com.newhan.chatservice.dto.userdtos.UserStatusUpdateEvent
spring.kafka.consumer.properties.spring.json.trusted.packages=*

# Producer Config (To send messages if needed)
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer