spring.application.name=newhanchat
spring.data.mongodb.uri=mongodb://localhost:27017/chatdb
jwt.secret=your-super-secret-and-long-key-that-is-not-nyakyv-taen-klyuch

spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.consumer.group-id=newhanchat-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer