spring.application.name=userservice

# --- DATABASE ---
spring.datasource.url=jdbc:postgresql://postgres:5432/newhan_users
spring.datasource.username=admin
spring.datasource.password=admin123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# --- KAFKA CONFIGURATION ---
spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.consumer.group-id=user-service-group
spring.kafka.consumer.auto-offset-reset=earliest

# 1. Key Deserializer
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# 2. Value Deserializer (Using ErrorHandling so bad messages don't crash the app)
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer

# 3. Map the Chat Service DTO to the User Service DTO
spring.kafka.consumer.properties.spring.json.type.mapping=com.newhan.chatservice.dto.userdtos.UserStatusUpdateEvent:com.newhan.userservice.dto.UserStatusUpdateEvent
spring.kafka.consumer.properties.spring.json.trusted.packages=*

# --- UPLOADS & JWT ---
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=15MB

jwt.secret=your-super-secret-and-long-key-that-is-not-nyakyv-taen-klyuch
jwt.expiration=86400000